title: Pentaho Platform JavaScript APIs
description: > # this means to ignore newlines in this property's value
  JavaScript component development for the Pentaho platform.

titleHtml: Pentaho Platform JavaScript APIs <sup><em>beta</em></sup>

theme: jekyll-theme-cayman

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

safe: true

# JsDoc 3 Urls are like:
#
# * Namespace: http://localhost:8000/pentaho.type.html
# * TypeDef:   http://localhost:8000/pentaho.type.html#Factory
# * Class:     http://localhost:8000/pentaho.type.Complex.html
# * Property:  http://localhost:8000/pentaho.type.Complex.html#changeset
#
# In Mindtouch, the ".html" is removed.
#
# Usage is like:
# * Namespace: {{site.refDocsUrlPattern | replace: '$', 'pentaho.type'}}
# * TypeDef:   {{site.refDocsUrlPattern | replace: '$', 'pentaho.type' | append: '#Factory'}}
# * Class:     {{site.refDocsUrlPattern | replace: '$', 'pentaho.type.Complex'}}
# * Property:  {{site.refDocsUrlPattern | replace: '$', 'pentaho.type.Complex' | append: '#changeset'}}
refDocsUrlPattern: https://help.pentaho.com/Documentation/8.0/Developer_Center/JavaScript_API/platform/$

starNew: ‚≠ê

# Base URL for Platform samples:
platformSamplesBaseUrl: https://github.com/pentaho/pentaho-engineering-samples/tree/master/Samples_for_Extending_Pentaho/
